### ISSUE TITLE
Please upload the file "caffe/util/modified_permutohedral.hpp"

### ISSUE THREAD

**Issue by huqiaoping** [ZhiwenShao/ARL#1]
Hi,

Thanks for your code.

The _**caffe/util/modified_permutohedral.hpp**_ should be used by _**meanfield_iteration.hpp**_ . Maybe you forgot to upload this file.

**Comment by ZhiwenShao** [comment]
Thanks for your reminding. I have uploaded modified_permutohedral.hpp and modified_permutohedral.cpp.

**Comment by huqiaoping** [comment]
Great! Thanks~

**Comment by huqiaoping** [comment]
Maybe you also forgot the file "caffe/util/tvg_util.hpp" ?

**Comment by ZhiwenShao** [comment]
Thanks. This file has been uploaded.

**Comment by huqiaoping** [comment]
The two files spatial.par and bilateral.par should be available. I think you forgot these two files.

**Comment by ZhiwenShao** [comment]
The two files have been uploaded. Thanks for testing the code.

**Comment by huqiaoping** [comment]
Thanks for your code. I can train now. *★,°*:.☆(￣▽￣)/$:*.°★*
